spring:
  security:
    jwt:
      key: abcdefg
      expire: 3
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123scc
    url: jdbc:mysql://dock01:3306/test
  data:
    redis:
      database: 0
      host: 192.168.171.199
      port: 6379
      password: 123scc